### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by marcinwysocki** [marcinwysocki/loadex#8]
This project started as a quick, ad-hock solution of a real world problem - load testing a particular application, using some specific workflows, that were very difficult to handle for popular tools like JMeter, due to a large amount of concurrent TCP connections having to be maintained for the duration of said workflows. An additional goal was to make it easy to define custom testing scenarios using plain Elixir and existing libraries from it's ecosystem. 

Both of these goals have been acomplished, but `Loadex` has since remained a side project. While it's battle tested, potential users have to take my word for it, as there's no unit or integration tests. There's not much documentation. Finally, there are some features, that haven't been implemented only because of time restrictions, but their inclusion would make a lot of sense for a lot of use cases. 

The new goal for this project should be to first, reach maturity and then to be released to Hex. Here is a roadmap for the nearest future.

Hex release (`0.1.0`) - November 2021:

- [x] documentation _at least_ for `Loadex` and `Loadex.Scenario` modules
- [x] tests covering all the implemented functionality

Next minor releases - late 2021:

- [ ] allowing scenarios to receive and act on messages
- [ ] more user friendly `setup`, i.e. returning a list of seed values and keeping `Spec` struct as an implementation detail, with deprecation of the old API
- [ ] an API for creating a sequence of `loops`/`wait_fors`
- [ ] improved loops API (see #14 )
- [ ] metrics

`1.0.0` (scope may change) - ???
- [ ] more flexible setup options, with something like `setup` and `setup_all` (__breaking change__)
- [ ] removal of depracated APIs (__breaking change__)
- [ ] running `Loadex` as an executable 
- [ ] ensure support of the latest OTP and Elixir versions
- [ ] mix task to run scenarios
